ingress:
  ## Set to true to enable ingress record generation
  ##
  enabled: false

  ## Set this to true in order to add the corresponding annotations for cert-manager
  ##
  certManager: true

  ## Ingress Path type
  ##
  pathType: ImplementationSpecific

  ## Override API Version (automatically detected if not set)
  ##
  apiVersion:

  ## When the ingress is enabled, a host pointing to this will be created
  ##
  hostname: grafana.51-158-129-164.lb.nl-ams.scw.cloud

  tls: true
admin:
  ## Admin username
  ##
  user: "admin"
  ## Admin password
  ## If a password is not provided a random password will be generated
  ##
  password: "admin"
service:
  ## K8s service type
  ##
  type: NodePort
  ## Grafana service port
  ##
  port: 3000
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort: 30002