ingress:
  ## Set to true to enable ingress record generation
  ##
  enabled: true

  ## Set this to true in order to add the corresponding annotations for cert-manager
  ##
  certManager: true

  ## Ingress Path type
  ##
  pathType: ImplementationSpecific

  ## Override API Version (automatically detected if not set)
  ##
  apiVersion:

  ## When the ingress is enabled, a host pointing to this will be created
  ##
  hostname: grafana.51-158-131-119.lb.nl-ams.scw.cloud

  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
admin:
  ## Admin username
  ##
  user: "admin"
  ## Admin password
  ## If a password is not provided a random password will be generated
  ##
  password: "admin"
