server:
  #extraArgs:
   # - --auth-mode=sso
  ingress:
    enabled: true

    ## Annotations to be added to the web ingress.
    ##
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"

    ## Hostnames.
    ## Must be provided if Ingress is enabled.
    ##
    hosts:
      - argo.51-158-129-164.lb.nl-ams.scw.cloud
useDefaultArtifactRepo: true
controller:
  containerRuntimeExecutor: pns
artifactRepository:
  # archiveLogs will archive the main container logs as an artifact
  archiveLogs: false
 # gcs:
 #   bucket: g3s-argo
 #   keyFormat: "{{workflow.namespace}}/{{workflow.name}}/"
 #   serviceAccountKeySecret:
 #     name: my-gcs-credentials
 #     key: serviceAccountKey
#images: 
#  tag: v2.12.5
minio:
  # If set to true then chart installs minio and generate according artifactRepository section in workflow controller config map
  install: true